site_name: Spark Delta MinIO
site_description: Pipeline Spark com Delta Lake e MinIO
theme:
  name: readthedocs
nav:
  - Inicio: index.md
  - Arquitetura: arquitetura.md
  - Execucao: execucao.md
  - Notebooks: notebooks.md
  - Tabelas gerenciadas: tabelas-gerenciadas.md
